# Generated by Django 5.1.14 on 2025-12-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_subscriptionprice_featured_subscriptionprice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
