# Generated by Django 5.1.14 on 2025-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscriptionprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1, help_text='Only one price per ordering can be featured at a time.'),
        ),
    ]
