# Generated by Django 5.1.14 on 2025-12-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_subscriptionprice_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
